### ISSUE TITLE
Distance + Movingtime ist NULL

### ISSUE THREAD

**Issue by lindi200000** [basti4557/ioBroker.komoot#2]
Hallo,
mir ist aufgefallen, das Distance und MovingTime keine Werte ausgibt, es steht immer NULL.
Ich habe Version 0.3.7
NPM 6.14.17
Node-JS v14.18.1
JS-Controller 4.0.23

![image](https://user-images.githubusercontent.com/16406425/195657310-c0de6a76-087f-4e81-ba6f-7d0d225bcd51.png)

Falls weitere Daten gebraucht werden, einfach melden.

Danke schonmal

**Comment by basti4557** [comment]
Schau dir mal Version 0.4.0 an. Da die Komoot Api leider nicht für die Öffentlichkeit freigegeben wird, werden die Inhalte direkt über die Website ausgelesen. Dort ändern sich ständig die Selektoren. Ich habe nun die Selektoren ausgelagert und der Adapter wird täglich die neusten Selektoren von Github herunterladen, sodass bei solchen Änderungen kein Adapter Update mehr nötig ist. (https://github.com/basti4557/ioBroker.komoot/blob/main/config/html-selectors.json)
