### ISSUE TITLE
Moving time and total distance not Working

### ISSUE THREAD

**Issue by locito09** [basti4557/ioBroker.komoot#3]
Moving time and total distance not Working

THX for the Adapter

**Comment by basti4557** [comment]
Hi,

has been fixed in [278f417](https://github.com/basti4557/ioBroker.komoot/commit/278f41712220024f1ace4d3c19bf0b6bbf166bf1)

You dont have to update the adapter, you can wait a day or just restart the adapter. He will syncronize his local json file than with the one on github :)

**Comment by locito09** [comment]
Thx
