### ISSUE TITLE
302 im log

### ISSUE THREAD

**Issue by bahnuhr** [basti4557/ioBroker.komoot#5]
Im log kommt:
<html>
<body>

komoot.0 | 2024-02-25 11:01:01.042 | error | Error while discovering the user id.
-- | -- | -- | --
komoot.0 | 2024-02-25 11:01:01.042 | warn | Status 302: www.komoot.de/account/details

</body>
</html>

siehe auch im thread:
https://forum.iobroker.net/topic/50467/neuer-adapter-komoot-anbindung/16

Offensichtlich funktioniert der Adapter nicht mehr !

**Comment by basti4557** [comment]
Duplicate

**Comment by basti4557** [comment]
Duplicate
